# Lab 11 

# Punto A
Eliminacion hacia adelante

In [13]:
import numpy as np

A = np.array([[3 , -0.1, -0.2, 7.85], [0.1, 7, -0.3, -19.3], [0.3, -0.2, 10, 71.4]])

print "Sistema Ecuaciones Propuesto:\n"
print "Matriz A \n"
print A, "\n"

n=3

# Eliminación de Gauss Simple hacia adelante
for k in range(0, n-1):
    for i in range(k+1, n):
        factor = A[i,k] / (A[k,k] * 1.0)
        for j in range(k,n):
            A[i,j] = A[i,j] - factor * A[k,j]
        A[i,n] = A[i,n] - factor * A[k,n]

print "----Resultados----\n"
print "Matriz A \n"
print A

Sistema Ecuaciones Propuesto:

Matriz A 

[[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]] 

----Resultados----

Matriz A 

[[  3.          -0.1         -0.2          7.85      ]
 [  0.           7.00333333  -0.29333333 -19.56166667]
 [  0.           0.          10.01204188  70.08429319]]


# Punto B
Sustitucion hacia atras

In [14]:
import numpy as np

A = np.array([[3, -0.1, -0.2, 7.85], [0.1, 7, -0.3, -19.3], [0.3, -0.2, 10, 71.4]])
X = np.zeros((3,1))

print "Sistema Ecuaciones Propuesto:\n"
print "Matriz A \n"
print A, "\n"

n = 3  

# Sustitución hacia atrás
X[n-1] = A[n-1,n] / (A[n-1,n-1] * 1.0)

for i in range(n-1,-1,-1):
    sum = A[i,n]
    for j in range(i+1, n):
        sum = sum - A[i,j] * X[j]
    X[i] = sum / (A[i,i] * 1.0)
print "----Resultados----\n"
print "\n Matriz A \n"
print X

Sistema Ecuaciones Propuesto:

Matriz A 

[[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]] 

----Resultados----


 Matriz A 

[[ 3.0109619 ]
 [-2.45114286]
 [ 7.14      ]]
